# Generated by Django 3.1.3 on 2020-11-25 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.CharField(default=0, max_length=20, validators=[django.core.validators.MinLengthValidator(2, 'Name must be greater than 2 characters')]),
            preserve_default=False,
        ),
    ]
