# Generated by Django 3.1.3 on 2020-11-25 08:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20201125_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2, 'name must be greater than 2 characters')])),
            ],
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.category'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tag1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_1', to='restaurants.tag'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tag2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_2', to='restaurants.tag'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tag3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_3', to='restaurants.tag'),
        ),
    ]
