# Generated by Django 3.1.3 on 2020-11-26 03:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20201125_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(1, 'value: $ $$ $$$ $$$$')])),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'rating >= 0'), django.core.validators.MaxValueValidator(10, 'rating <= 10')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.price'),
        ),
    ]
