# Generated by Django 3.1.3 on 2020-11-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20201126_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='pic1',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
