# Generated by Django 3.1.3 on 2020-11-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_restaurant_pic1'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='pic2',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='pic3',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
